version: '3.8'

services:
  weather-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: weather-app-dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code để dev không cần rebuild
      - ./Backend:/app
      - ./Frontend:/app/Frontend
      # Prevent overwriting node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    command: npm run dev  # Sử dụng nodemon hoặc similar
    networks:
      - weather-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  weather-network:
    driver: bridge

# Để chạy development mode:
# docker compose -f docker-compose.dev.yml up -d
